{
    'name': 'Home To Life',
    'version': '1.0',
    'sequence': -1,
    'category': '',
    'summary': '',
    'description': """""",
    'author': 'PlanetOdoo',
    'depends': ['base', 'product', 'sale', 'po_accounting_proforma_v16', 'crm', 'account', 'purchase',
                'sale_purchase_inter_company_rules', 'sale_purchase', 'purchase_stock', 'helpdesk', 'sale_stock', 'hr',
                'loyalty', 'sale_loyalty'],
    "data": [
        "data/email_template.xml",
        "data/customer_sequence.xml",
        "data/stock_cron.xml",
        "data/sale_confirmation.xml",
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/inherit_product_view.xml",
        "views/import_product.xml",
        "views/material_master.xml",
        "views/sale_order_line_view.xml",
        "views/connect_to_ftp.xml",
        "views/ftp_configuration.xml",
        "views/file_transfer_log.xml",
        "views/crm_view.xml",
        "views/inherit_account_payment.xml",
        "views/walking.xml",
        "views/inherit_res_partner.xml",
        "views/inherit_account_move_line.xml",
        "views/purchase_order.xml",
        "views/franchise_margin.xml",
        "views/ftp_stock.xml",
        "views/helpdesk.xml",
        "views/inherit_loyalty.xml",
        "views/ad_set_views.xml",
        "views/inherit_utm.xml",
        "wizard/so_report.xml",
        "wizard/mtd_report.xml",
        "report/inherit_purchase_order_report.xml",
        "report/report_invoice_template.xml",
        "report/inherit_sale_order_report.xml",
    ],
    "assets": {
        "web.assets_backend": [

        ],
        "web.assets_qweb": [

        ],
    },
    'website': 'https://planet-odoo.com/',
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
