from . import product_product
from . import import_product
from . import material_master
from . import sale_order_line
from . import inherit_product_template
from . import import_product_price
from . import connect_to_ftp
from . import ftp_configuration
from . import res_partner
from . import file_transfer_log
from . import crm
from . import inherit_account_payment
from . import walkings
from . import sale_order_inherit
from . import inherit_account_move_line
from . import inherit_account_move
from . import purchase_order
from . import franchise_margin
from . import inherit_stock_rule
from . import ftp_stock
from . import inherit_helpdesk
from . import inherit_loyalty
from . import import_vendor_pricelist
from . import ad_set
from . import utm_models

